wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.12
    start_time: 1641203392
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 13
      - 16
      4: 3.8.12
      5: 0.12.9
      8:
      - 2
      - 5
act_fn:
  desc: null
  value: relu
attention_decoder:
  desc: null
  value: false
batch_size:
  desc: null
  value: 32
checkpoint_decoder:
  desc: null
  value: ./out/checkpoint/decoder.pt
checkpoint_stdgi:
  desc: null
  value: ./out/checkpoint/stdgi.pt
cnn_hid_dim:
  desc: null
  value: 128
delta_decoder:
  desc: null
  value: 0
delta_stdgi:
  desc: null
  value: 0
dis_hid:
  desc: null
  value: 6
en_hid1:
  desc: null
  value: 200
en_hid2:
  desc: null
  value: 400
fc_hid_dim:
  desc: null
  value: 64
features:
  desc: null
  value:
  - PM2.5
  - AQI
  - PM10
  - CO
  - O3
  - SO2
  - NO2
  - Change
  - wind
input_dim:
  desc: null
  value: 9
interpolate:
  desc: null
  value: false
loss:
  desc: null
  value: mse
lr_decoder:
  desc: null
  value: 0.005
lr_stdgi:
  desc: null
  value: 0.005
n_layers_rnn:
  desc: null
  value: 1
num_epochs_decoder:
  desc: null
  value: 0
num_epochs_stdgi:
  desc: null
  value: 0
output_dim:
  desc: null
  value: 1
output_path:
  desc: null
  value: ./out/
output_stdgi:
  desc: null
  value: 60
patience:
  desc: null
  value: 3
rnn_type:
  desc: null
  value: LSTM
seed:
  desc: null
  value: 52
sequence_length:
  desc: null
  value: 12
test_station:
  desc: null
  value:
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
train_station:
  desc: null
  value:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
